### ISSUE TITLE
Feature request: include read mails in the generated report

### ISSUE THREAD

**Issue by m09** [bzz/scholar-alert-digest#10]
Cf discussion starting with https://github.com/bzz/scholar-alert-digest/pull/9#issuecomment-559499679

**Comment by m09** [comment]
For the CLI argument, I'd use `-all`, for the markdown template:

**Comment by bzz** [comment]
Awesome, thank you so much for the details!
I'll add it asap.

Quick question - right now the report include an occurrence count for each title across all unread emails. How useful that is and do you think it would be worth keeping it and making separate between the report sections? Or keep it total?

My intuition is that it might be not that useful for  Archive section so may not be worth the complexity of adding one there at all.

On the CLI flag, I was thinking of calling it something related to adding/including the read emails, but all seems to be to the same effect as well :+1:

**Comment by m09** [comment]
I think it can be useful for the unread section, with the total amount. Not strong opinion either way though.

**Comment by bzz** [comment]
> I think it can be useful for the unread section, with the total amount. Not strong opinion either way though.

Basically, count stats over total emails, but only show it for the non-archive section?

Anyway, thanks for the input, it is much appreciated!
Now that we have  `-mark` #5 done,  I'll take a stab at initial version of this later today.
