### ISSUE TITLE
Full duplicates in the output

### ISSUE THREAD

**Issue by jzuken** [bzz/scholar-alert-digest#12]
Occasionally there are duplicates in the tool output:

<img width="611" alt="Screenshot 2019-12-06 at 11 17 38" src="https://user-images.githubusercontent.com/705678/70307354-04627880-181a-11ea-8d20-6fcf2359e7fb.png">

Is it a bug or a feature? :)

**Comment by bzz** [comment]
> Is it a bug or a feature? :)

Thank you for reporting! From the first glance, that seem like a bug to me. 
If you could attach a gist with the full Markdown report - I'll be happy to take a deeper look.

**Comment by jzuken** [comment]
Sure: https://gist.github.com/jzuken/3223bc3fe0bb2abcf0a70431a100f636

They seem to have different URLs, but exactly the same title. AFAIK, Scholar groups papers with matching substrings in titles (e.g. [this paper](https://scholar.google.com/citations?hl=ru&user=Ra4bt-oAAAAJ#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Dru%26user%3DRa4bt-oAAAAJ%26citation_for_view%3DRa4bt-oAAAAJ%3AzA6iFVUQeVQC%26tzom%3D-180) has 12 versions). This might be too much, just grouping the exact matches would be awesome.

**Comment by bzz** [comment]
Was closed by the automation on merging #16. 
@jzuken would you be so kind and test the latest master to see if it fixes the issue for you? Thanks!

**Comment by jzuken** [comment]
Looks good now, thank you!
