### ISSUE TITLE
feature request: visible authors 

### ISSUE THREAD

**Issue by jzuken** [bzz/scholar-alert-digest#29]
In the current implementation, authors are always hidden and are shown only when abstracts are expanded. If someone is interested in authors much more than in abstracts, it requires them to click a lot to see all of the authors.

As a workaround, maybe the authors could be shown in between the title and the abstract? 

<img width="757" alt="Screenshot 2019-12-23 at 12 40 40" src="https://user-images.githubusercontent.com/705678/71350037-714b7180-2581-11ea-9d6d-71bee9000871.png">

But I guess it makes the normal mode even less compact. :) So another way is to add the authors after the title like this:

<img width="1093" alt="Screenshot 2019-12-23 at 12 55 00" src="https://user-images.githubusercontent.com/705678/71350905-6f82ad80-2583-11ea-9bd9-79af1ac8a60b.png">

<img width="1091" alt="Screenshot 2019-12-23 at 12 49 24" src="https://user-images.githubusercontent.com/705678/71350619-aefcca00-2582-11ea-9396-7237285fb93c.png">

Would this pattern introduce less noise?

**Comment by bzz** [comment]
Got the idea, will change `-authors` to display author names \wo a click 👌.

I just wonder what would be a way to reconcile this with #13 🤔  
(even with the current numbers instead of people names in just landed `-refs`, these 19 are going to be looong)

**Comment by bzz** [comment]
Closing as #30 is merged now.

**Comment by jzuken** [comment]
Awesome! Thank you
