### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by marwahaha** [bzz/scholar-alert-digest#56]
When following the initial instruction (I think this is the go get step), I get
```
(base) kunal@kunal-hp:/tmp/tmp.84voCCm03m$ go get github.com/bzz/scholar-alert-digest
go: finding github.com/bzz/scholar-alert-digest latest
go: downloading github.com/bzz/scholar-alert-digest v0.0.0-20210307170856-bfb769eb3f3c
go: extracting github.com/bzz/scholar-alert-digest v0.0.0-20210307170856-bfb769eb3f3c
go get: github.com/bzz/scholar-alert-digest@v0.0.0-20210307170856-bfb769eb3f3c requires
	gitlab.com/golang-commonmark/markdown@v0.0.0-20191124021542-fffb4bed7d15 requires
	gopkg.in/russross/blackfriday.v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

How can I debug it?

**Comment by bzz** [comment]
Hi @marwahaha - sorry for confusion, the installation that includes use Go tooling to build the binary indeed can be a bit tricky to debug.

While I'm looking into it, I think it is a better to follow the "development" workflow
> or run it directly from the clone of the sources using go command, as described below.

by just cloning the repository manually and following the `go run` commands from READEM. 
AFAIK that's what most people been using, at least until we put some effort into release engineering and provide a better binary artifacts.

**Comment by marwahaha** [comment]
Ok, thanks, I've got it working.
